name: Feature Request
description: Suggest an idea for this project.
title: "[Feature Request] "
labels:
  - "type: enhancement"
  - "resolution: unresolved"
  - "status: pending"
body:
  - type: markdown
    attributes:
      value: "**Note: Please fill this request truthfully, otherwise your issue may be closed, locked or deleted directly.**"

  - type: checkboxes
    id: before_requesting
    attributes:
      label: Before requesting
      options:
        - label: I have known and agreed that I would fill this request truthfully, or my issue may be closed, locked or deleted unconditionally.
          required: true
        - label: I have searched for existing issues (including `Open` and `Closed`).
          required: true
        - label: I am using the latest CI build of AdvancedVelocityManager.
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description of the new features
    validations:
      required: true

  - type: textarea
    id: necessity
    attributes:
      label: The necessity of the new features
      description: Why do you think the new features or new changes is needed?
    validations:
      required: true

  - type: textarea
    id: relevant_problems
    attributes:
      label: The problems related to the new features
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
